add exit call status check

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,3 +2,8 @@
 
 echo "Running tests"
 ./bin/dev.sh test
+if [ $? != 0 ]; then
+    echo "One or more tests failed! Commit cancelled."
+    echo "To bypass, use the --no-verify flag."
+    exit $?
+fi
